import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { FlatCompat } from '@eslint/eslintrc'
import i18next from 'eslint-plugin-i18next'

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) })

const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      // Generated by Next on every build and gitignored.
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  // PLAN.md §4: no user-visible string may be hard-coded. Everything rendered
  // lives in messages/{en,es}.json so both languages stay in lockstep.
  {
    files: ['src/app/**/*.tsx', 'src/components/**/*.tsx'],
    plugins: { i18next },
    rules: {
      'i18next/no-literal-string': [
        'error',
        {
          mode: 'jsx-text-only',
          'should-validate-template': true,
        },
      ],
    },
  },
  // The domain engine is pure: it may not reach for the framework or the database.
  {
    files: ['src/domain/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            { group: ['next', 'next/*', 'react', 'react-*'], message: 'src/domain must stay framework-free (PLAN.md §2).' },
            { group: ['@supabase/*', '@/lib/*', '@/app/*'], message: 'src/domain must stay free of I/O (PLAN.md §2).' },
          ],
        },
      ],
    },
  },
]

export default config
