import { NextResponse, type NextRequest } from 'next/server'
import type { EmailOtpType } from '@supabase/supabase-js'
import { defaultLocale, isLocale } from '@/i18n/routing'
import { safeRedirectPath } from '@/lib/auth/routes'
import { createClient } from '@/lib/supabase/server'

const OTP_TYPES: ReadonlySet<string> = new Set(['magiclink', 'email', 'signup', 'recovery', 'invite', 'email_change'])

/**
 * Where magic links and OAuth redirects land.
 *
 * Two ways in, both of which end with the session written to cookies:
 *   - `code`: the PKCE exchange, which is what a link sent by this app's own
 *     sign-in form comes back with.
 *   - `token_hash` + `type`: direct verification of an email OTP, the pattern
 *     Supabase documents for server-rendered apps. It needs no redirect through
 *     the auth server, so it also works for links generated by the admin API.
 *
 * Either way the visitor is then sent where they were headed — validated
 * first, so a crafted `next` cannot bounce them off-site with a fresh session.
 */
export async function GET(request: NextRequest) {
  const { searchParams, origin } = new URL(request.url)
  const localeParam = searchParams.get('locale')
  const locale = localeParam && isLocale(localeParam) ? localeParam : defaultLocale
  const next = safeRedirectPath(searchParams.get('next'), locale)

  const code = searchParams.get('code')
  const tokenHash = searchParams.get('token_hash')
  const type = searchParams.get('type')

  const supabase = await createClient()

  if (code) {
    const { error } = await supabase.auth.exchangeCodeForSession(code)
    if (error) return NextResponse.redirect(`${origin}/${locale}/sign-in?error=exchange_failed`)
    return NextResponse.redirect(`${origin}${next}`)
  }

  if (tokenHash && type && OTP_TYPES.has(type)) {
    const { error } = await supabase.auth.verifyOtp({ token_hash: tokenHash, type: type as EmailOtpType })
    if (error) return NextResponse.redirect(`${origin}/${locale}/sign-in?error=exchange_failed`)
    return NextResponse.redirect(`${origin}${next}`)
  }

  return NextResponse.redirect(`${origin}/${locale}/sign-in?error=missing_code`)
}
