import type { ExerciseDefinition } from './types'

const ALL = ['full_gym', 'dumbbells_bench', 'home_none'] as const
const GYM = ['full_gym'] as const
const GYM_DB = ['full_gym', 'dumbbells_bench'] as const

/**
 * The exercise library.
 *
 * Authored for Plates & Pace rather than ported from the prototype, which was
 * not available. Ratios are reference working loads for a male intermediate
 * lifter as a fraction of bodyweight; sex and experience factors are applied
 * by the load engine. Dumbbell ratios are per hand.
 */
export const EXERCISES: readonly ExerciseDefinition[] = [
  // ------------------------------------------------------------ quads --
  { id: 'back_squat', primary: 'quads', secondary: ['glutes'], region: 'lower', implement: 'barbell', equipment: GYM, patterns: ['deep_knee_flexion', 'spinal_loading'], strengthRatio: 1.0, minTier: 'intermediate', bigLift: true, category: 'compound', animation: 'squat' , movement: 'squat', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '3010', breathing: 'brace', regressions: ['goblet_squat', 'leg_press'], progressions: ['front_squat'], mediaId: 'Barbell_Squat' },
  { id: 'front_squat', primary: 'quads', secondary: ['abs'], region: 'lower', implement: 'barbell', equipment: GYM, patterns: ['deep_knee_flexion', 'spinal_loading', 'loaded_wrist_extension'], strengthRatio: 0.8, minTier: 'advanced', bigLift: true, category: 'compound', animation: 'front_squat' , movement: 'squat', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '3010', breathing: 'brace', regressions: ['back_squat', 'goblet_squat'], mediaId: 'Front_Barbell_Squat' },
  { id: 'goblet_squat', primary: 'quads', secondary: ['glutes'], region: 'lower', implement: 'dumbbell', equipment: GYM_DB, patterns: ['deep_knee_flexion'], strengthRatio: 0.35, minTier: 'beginner', category: 'compound', animation: 'goblet_squat' , movement: 'squat', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '3010', breathing: 'brace', regressions: ['bodyweight_squat'], progressions: ['back_squat', 'hack_squat'], mediaId: 'Goblet_Squat' },
  { id: 'leg_press', primary: 'quads', secondary: ['glutes'], region: 'lower', implement: 'machine', equipment: GYM, patterns: ['deep_knee_flexion'], strengthRatio: 1.8, minTier: 'beginner', category: 'compound', machineId: 'leg_press', animation: 'leg_press' , movement: 'squat', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', materials: ['machine'], regressions: ['bodyweight_squat'], progressions: ['hack_squat', 'back_squat'], mediaId: 'Leg_Press' },
  { id: 'hack_squat', primary: 'quads', secondary: ['glutes'], region: 'lower', implement: 'machine', equipment: GYM, patterns: ['deep_knee_flexion'], strengthRatio: 1.0, minTier: 'intermediate', category: 'compound', machineId: 'hack_squat', animation: 'hack_squat' , movement: 'squat', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '3010', breathing: 'brace', materials: ['machine'], regressions: ['leg_press', 'goblet_squat'], progressions: ['back_squat'], mediaId: 'Hack_Squat' },
  { id: 'bulgarian_split_squat', primary: 'quads', secondary: ['glutes'], region: 'lower', implement: 'dumbbell', equipment: GYM_DB, patterns: ['loaded_lunge', 'deep_knee_flexion'], strengthRatio: 0.25, minTier: 'intermediate', category: 'compound', animation: 'split_squat', unilateral: true , movement: 'lunge', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '3010', breathing: 'exhale_effort', materials: ['bench'], regressions: ['split_squat', 'reverse_lunge'], progressions: ['pistol_squat'] },
  { id: 'walking_lunge', primary: 'quads', secondary: ['glutes'], region: 'lower', implement: 'dumbbell', equipment: GYM_DB, patterns: ['loaded_lunge'], strengthRatio: 0.2, minTier: 'beginner', category: 'accessory', animation: 'lunge', unilateral: true , movement: 'lunge', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2010', breathing: 'exhale_effort', regressions: ['reverse_lunge', 'split_squat'], progressions: ['bulgarian_split_squat'], mediaId: 'Bodyweight_Walking_Lunge' },
  { id: 'step_up', primary: 'quads', secondary: ['glutes'], region: 'lower', implement: 'dumbbell', equipment: GYM_DB, patterns: ['loaded_lunge'], strengthRatio: 0.2, minTier: 'beginner', category: 'accessory', animation: 'step_up', unilateral: true , movement: 'lunge', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', materials: ['box'], regressions: ['bodyweight_squat'], progressions: ['bulgarian_split_squat'], mediaId: 'Dumbbell_Step_Ups' },
  { id: 'bodyweight_squat', primary: 'quads', secondary: ['glutes'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: ['deep_knee_flexion'], strengthRatio: 0, minTier: 'beginner', category: 'compound', animation: 'squat' , movement: 'squat', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '3010', breathing: 'exhale_effort', regressions: ['deep_squat_hold'], progressions: ['goblet_squat', 'split_squat', 'pistol_squat'], mediaId: 'Bodyweight_Squat' },
  { id: 'reverse_lunge', primary: 'quads', secondary: ['glutes'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: ['loaded_lunge', 'deep_knee_flexion'], strengthRatio: 0, minTier: 'beginner', category: 'accessory', animation: 'lunge', unilateral: true , movement: 'lunge', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', regressions: ['split_squat', 'step_up'], progressions: ['walking_lunge', 'bulgarian_split_squat'] },
  { id: 'leg_extension', primary: 'quads', secondary: [], region: 'lower', implement: 'machine', equipment: GYM, patterns: ['knee_extension_loaded'], strengthRatio: 0.5, minTier: 'beginner', category: 'isolation', machineId: 'leg_extension', animation: 'leg_extension' , movement: 'isolation', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['machine'], progressions: ['sissy_squat'], mediaId: 'Leg_Extensions' },

  // ------------------------------------------------ hamstrings / hinge --
  { id: 'conventional_deadlift', primary: 'hamstrings', secondary: ['glutes', 'back'], region: 'lower', implement: 'barbell', equipment: GYM, patterns: ['loaded_hip_hinge', 'spinal_loading'], strengthRatio: 1.2, minTier: 'intermediate', bigLift: true, category: 'compound', animation: 'deadlift' , movement: 'hinge', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'low', tempo: '2010', breathing: 'brace', regressions: ['trap_bar_deadlift', 'romanian_deadlift'], progressions: ['sumo_deadlift'], mediaId: 'Barbell_Deadlift' },
  { id: 'romanian_deadlift', primary: 'hamstrings', secondary: ['glutes'], region: 'lower', implement: 'barbell', equipment: GYM, patterns: ['loaded_hip_hinge'], strengthRatio: 0.8, minTier: 'intermediate', category: 'compound', animation: 'hinge' , movement: 'hinge', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '3010', breathing: 'brace', regressions: ['dumbbell_rdl'], progressions: ['conventional_deadlift', 'good_morning'], mediaId: 'Romanian_Deadlift' },
  { id: 'dumbbell_rdl', primary: 'hamstrings', secondary: ['glutes'], region: 'lower', implement: 'dumbbell', equipment: GYM_DB, patterns: ['loaded_hip_hinge'], strengthRatio: 0.3, minTier: 'beginner', category: 'compound', animation: 'hinge' , movement: 'hinge', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '3010', breathing: 'brace', regressions: ['glute_bridge', 'cable_pull_through'], progressions: ['romanian_deadlift', 'single_leg_rdl'] },
  { id: 'leg_curl', primary: 'hamstrings', secondary: [], region: 'lower', implement: 'machine', equipment: GYM, patterns: [], strengthRatio: 0.4, minTier: 'beginner', category: 'isolation', machineId: 'leg_curl', animation: 'leg_curl' , movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['machine'], progressions: ['nordic_curl', 'glute_ham_raise'], mediaId: 'Lying_Leg_Curls' },
  { id: 'nordic_curl', primary: 'hamstrings', secondary: [], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'advanced', category: 'accessory', animation: 'nordic' , movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'low', tempo: '4010', breathing: 'exhale_effort', regressions: ['leg_curl', 'glute_bridge'], progressions: ['glute_ham_raise'], mediaId: 'Natural_Glute_Ham_Raise' },

  // ----------------------------------------------------------- glutes --
  { id: 'hip_thrust', primary: 'glutes', secondary: ['hamstrings'], region: 'lower', implement: 'barbell', equipment: GYM, patterns: [], strengthRatio: 1.0, minTier: 'beginner', category: 'compound', animation: 'hip_thrust' , movement: 'hinge', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['bench'], regressions: ['dumbbell_hip_thrust', 'glute_bridge'], mediaId: 'Barbell_Hip_Thrust' },
  { id: 'dumbbell_hip_thrust', primary: 'glutes', secondary: ['hamstrings'], region: 'lower', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.4, minTier: 'beginner', category: 'compound', animation: 'hip_thrust' , movement: 'hinge', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['bench'], regressions: ['glute_bridge'], progressions: ['hip_thrust'] },
  { id: 'glute_bridge', primary: 'glutes', secondary: ['hamstrings'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'accessory', animation: 'bridge' , movement: 'hinge', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', regressions: ['glute_bridge_hold'], progressions: ['single_leg_glute_bridge', 'dumbbell_hip_thrust'], mediaId: 'Butt_Lift_Bridge' },
  { id: 'cable_kickback', primary: 'glutes', secondary: [], region: 'lower', implement: 'cable', equipment: GYM, patterns: [], strengthRatio: 0.15, minTier: 'beginner', category: 'isolation', animation: 'kickback', unilateral: true , movement: 'isolation', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['cable'], regressions: ['single_leg_glute_bridge'], progressions: ['hip_thrust'], mediaId: 'Glute_Kickback' },
  { id: 'hip_abduction', primary: 'glutes', secondary: [], region: 'lower', implement: 'machine', equipment: GYM, patterns: [], strengthRatio: 0.5, minTier: 'beginner', category: 'isolation', machineId: 'hip_abduction', animation: 'abduction' , movement: 'isolation', force: 'push', plane: 'frontal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['machine'], mediaId: 'Thigh_Abductor' },
  { id: 'single_leg_glute_bridge', primary: 'glutes', secondary: ['hamstrings'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'accessory', animation: 'bridge', unilateral: true , movement: 'hinge', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', regressions: ['glute_bridge'], progressions: ['dumbbell_hip_thrust'], mediaId: 'Single_Leg_Glute_Bridge' },

  // ----------------------------------------------------------- calves --
  { id: 'standing_calf_raise', primary: 'calves', secondary: [], region: 'lower', implement: 'machine', equipment: GYM, patterns: [], strengthRatio: 1.0, minTier: 'beginner', category: 'isolation', machineId: 'calf_raise', animation: 'calf_raise' , movement: 'isolation', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2012', breathing: 'continuous', materials: ['machine'], regressions: ['bodyweight_calf_raise'], mediaId: 'Standing_Calf_Raises' },
  { id: 'dumbbell_calf_raise', primary: 'calves', secondary: [], region: 'lower', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.3, minTier: 'beginner', category: 'isolation', animation: 'calf_raise' , movement: 'isolation', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2012', breathing: 'continuous', regressions: ['bodyweight_calf_raise'], progressions: ['single_leg_calf_raise', 'standing_calf_raise'], mediaId: 'Standing_Dumbbell_Calf_Raise' },
  { id: 'bodyweight_calf_raise', primary: 'calves', secondary: [], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'isolation', animation: 'calf_raise' , movement: 'isolation', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2012', breathing: 'continuous', regressions: ['calf_stretch'], progressions: ['single_leg_calf_raise', 'dumbbell_calf_raise'] },

  // ------------------------------------------------------------ chest --
  { id: 'bench_press', primary: 'chest', secondary: ['triceps', 'shoulders'], region: 'upper', implement: 'barbell', equipment: GYM, patterns: [], strengthRatio: 0.75, minTier: 'intermediate', bigLift: true, category: 'compound', animation: 'horizontal_push' , movement: 'horizontal_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2010', breathing: 'brace', materials: ['bench'], regressions: ['dumbbell_bench_press', 'push_up'], progressions: ['close_grip_bench_press', 'incline_bench_press'], mediaId: 'Barbell_Bench_Press_-_Medium_Grip' },
  { id: 'dumbbell_bench_press', primary: 'chest', secondary: ['triceps'], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.3, minTier: 'beginner', category: 'compound', animation: 'horizontal_push' , movement: 'horizontal_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', materials: ['bench'], regressions: ['push_up', 'chest_press_machine'], progressions: ['bench_press', 'incline_dumbbell_press'], mediaId: 'Dumbbell_Bench_Press' },
  { id: 'incline_dumbbell_press', primary: 'chest', secondary: ['shoulders'], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.25, minTier: 'beginner', category: 'compound', animation: 'incline_press' , movement: 'horizontal_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', materials: ['bench'], regressions: ['dumbbell_bench_press'], progressions: ['incline_bench_press'], mediaId: 'Incline_Dumbbell_Press' },
  { id: 'chest_press_machine', primary: 'chest', secondary: ['triceps'], region: 'upper', implement: 'machine', equipment: GYM, patterns: [], strengthRatio: 0.7, minTier: 'beginner', category: 'compound', machineId: 'chest_press', animation: 'seated_press' , movement: 'horizontal_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', materials: ['machine'], regressions: ['push_up'], progressions: ['dumbbell_bench_press'], mediaId: 'Machine_Bench_Press' },
  { id: 'push_up', primary: 'chest', secondary: ['triceps'], region: 'upper', implement: 'bodyweight', equipment: ALL, patterns: ['loaded_wrist_extension'], strengthRatio: 0, minTier: 'beginner', category: 'compound', animation: 'push_up' , movement: 'horizontal_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', regressions: ['incline_push_up'], progressions: ['decline_push_up', 'dip', 'dumbbell_bench_press'], mediaId: 'Pushups' },
  { id: 'cable_fly', primary: 'chest', secondary: [], region: 'upper', implement: 'cable', equipment: GYM, patterns: [], strengthRatio: 0.15, minTier: 'beginner', category: 'isolation', animation: 'fly' , movement: 'isolation', force: 'push', plane: 'transverse', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['cable'], regressions: ['dumbbell_fly'], mediaId: 'Cable_Crossover' },
  { id: 'dumbbell_fly', primary: 'chest', secondary: [], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.12, minTier: 'beginner', category: 'isolation', animation: 'fly_lying' , movement: 'isolation', force: 'push', plane: 'transverse', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '3010', breathing: 'exhale_effort', materials: ['bench'], progressions: ['cable_fly', 'machine_fly'], mediaId: 'Dumbbell_Flyes' },

  // -------------------------------------------------------- shoulders --
  { id: 'overhead_press', primary: 'shoulders', secondary: ['triceps'], region: 'upper', implement: 'barbell', equipment: GYM, patterns: ['overhead_press'], strengthRatio: 0.5, minTier: 'intermediate', category: 'compound', animation: 'vertical_push' , movement: 'vertical_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2010', breathing: 'brace', regressions: ['dumbbell_shoulder_press', 'landmine_press'], progressions: ['push_press'], mediaId: 'Standing_Military_Press' },
  { id: 'dumbbell_shoulder_press', primary: 'shoulders', secondary: ['triceps'], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: ['overhead_press'], strengthRatio: 0.2, minTier: 'beginner', category: 'compound', animation: 'vertical_push' , movement: 'vertical_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', regressions: ['machine_shoulder_press', 'pike_push_up'], progressions: ['overhead_press', 'arnold_press'], mediaId: 'Dumbbell_Shoulder_Press' },
  { id: 'machine_shoulder_press', primary: 'shoulders', secondary: ['triceps'], region: 'upper', implement: 'machine', equipment: GYM, patterns: ['overhead_press'], strengthRatio: 0.5, minTier: 'beginner', category: 'compound', machineId: 'shoulder_press', animation: 'vertical_push' , movement: 'vertical_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', materials: ['machine'], regressions: ['pike_push_up'], progressions: ['dumbbell_shoulder_press'], mediaId: 'Machine_Shoulder_Military_Press' },
  { id: 'pike_push_up', primary: 'shoulders', secondary: ['triceps'], region: 'upper', implement: 'bodyweight', equipment: ALL, patterns: ['overhead_press', 'loaded_wrist_extension'], strengthRatio: 0, minTier: 'beginner', category: 'compound', animation: 'pike_push_up' , movement: 'vertical_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', regressions: ['wall_slide'], progressions: ['dumbbell_shoulder_press'] },
  { id: 'lateral_raise', primary: 'shoulders', secondary: [], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.08, minTier: 'beginner', category: 'isolation', animation: 'lateral_raise' , movement: 'isolation', force: 'pull', plane: 'frontal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'continuous', progressions: ['cable_lateral_raise'], mediaId: 'Side_Lateral_Raise' },
  { id: 'face_pull', primary: 'shoulders', secondary: ['back'], region: 'upper', implement: 'cable', equipment: GYM, patterns: [], strengthRatio: 0.2, minTier: 'beginner', category: 'isolation', animation: 'face_pull' , movement: 'horizontal_pull', force: 'pull', plane: 'transverse', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'continuous', materials: ['cable'], regressions: ['band_pull_apart', 'rear_delt_fly'], mediaId: 'Face_Pull' },
  { id: 'rear_delt_fly', primary: 'shoulders', secondary: ['back'], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.08, minTier: 'beginner', category: 'isolation', animation: 'rear_delt_fly' , movement: 'isolation', force: 'pull', plane: 'transverse', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'continuous', regressions: ['band_pull_apart'], progressions: ['face_pull'], mediaId: 'Reverse_Flyes' },

  // ------------------------------------------------------------- back --
  { id: 'barbell_row', primary: 'back', secondary: ['biceps'], region: 'upper', implement: 'barbell', equipment: GYM, patterns: ['loaded_hip_hinge', 'spinal_loading'], strengthRatio: 0.6, minTier: 'intermediate', category: 'compound', animation: 'horizontal_pull' , movement: 'horizontal_pull', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2011', breathing: 'brace', regressions: ['chest_supported_row', 'dumbbell_row'], progressions: ['pendlay_row'], mediaId: 'Bent_Over_Barbell_Row' },
  { id: 'dumbbell_row', primary: 'back', secondary: ['biceps'], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.3, minTier: 'beginner', category: 'compound', animation: 'one_arm_row', unilateral: true , movement: 'horizontal_pull', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['bench'], regressions: ['inverted_row', 'seated_cable_row'], progressions: ['barbell_row'], mediaId: 'One-Arm_Dumbbell_Row' },
  { id: 'chest_supported_row', primary: 'back', secondary: ['biceps'], region: 'upper', implement: 'machine', equipment: GYM, patterns: [], strengthRatio: 0.6, minTier: 'beginner', category: 'compound', machineId: 'chest_supported_row', animation: 'seated_row' , movement: 'horizontal_pull', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['machine'], regressions: ['seated_cable_row'], progressions: ['dumbbell_row', 't_bar_row'] },
  { id: 'seated_cable_row', primary: 'back', secondary: ['biceps'], region: 'upper', implement: 'cable', equipment: GYM, patterns: [], strengthRatio: 0.6, minTier: 'beginner', category: 'compound', animation: 'seated_row' , movement: 'horizontal_pull', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['cable'], regressions: ['inverted_row'], progressions: ['chest_supported_row', 'barbell_row'], mediaId: 'Seated_Cable_Rows' },
  { id: 'lat_pulldown', primary: 'back', secondary: ['biceps'], region: 'upper', implement: 'machine', equipment: GYM, patterns: [], strengthRatio: 0.6, minTier: 'beginner', category: 'compound', machineId: 'lat_pulldown', animation: 'lat_pulldown' , movement: 'vertical_pull', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['machine'], regressions: ['straight_arm_pulldown'], progressions: ['assisted_pull_up', 'chin_up', 'pull_up'], mediaId: 'Wide-Grip_Lat_Pulldown' },
  { id: 'pull_up', primary: 'back', secondary: ['biceps'], region: 'upper', implement: 'bodyweight', equipment: GYM, patterns: [], strengthRatio: 0, minTier: 'advanced', category: 'compound', animation: 'vertical_pull' , movement: 'vertical_pull', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2011', breathing: 'exhale_effort', materials: ['bar'], regressions: ['chin_up', 'assisted_pull_up', 'lat_pulldown'], mediaId: 'Pullups' },
  { id: 'inverted_row', primary: 'back', secondary: ['biceps'], region: 'upper', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'compound', animation: 'inverted_row' , movement: 'horizontal_pull', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['bar'], regressions: ['suspension_row', 'superman'], progressions: ['dumbbell_row', 'chin_up'], mediaId: 'Inverted_Row' },
  { id: 'superman', primary: 'back', secondary: ['glutes'], region: 'core', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'accessory', animation: 'superman' , movement: 'anti_extension', force: 'static', plane: 'sagittal', purpose: 'stabilise', type: 'training', sfr: 'high', tempo: '2020', breathing: 'continuous', regressions: ['bird_dog'], progressions: ['back_extension', 'inverted_row'], mediaId: 'Superman' },

  // ------------------------------------------------------------- arms --
  { id: 'dumbbell_curl', primary: 'biceps', secondary: [], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.12, minTier: 'beginner', category: 'isolation', animation: 'curl' , movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'continuous', progressions: ['incline_dumbbell_curl', 'barbell_curl'], mediaId: 'Dumbbell_Bicep_Curl' },
  { id: 'hammer_curl', primary: 'biceps', secondary: [], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.12, minTier: 'beginner', category: 'isolation', animation: 'curl' , movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'continuous', progressions: ['barbell_curl'], mediaId: 'Hammer_Curls' },
  { id: 'cable_curl', primary: 'biceps', secondary: [], region: 'upper', implement: 'cable', equipment: GYM, patterns: [], strengthRatio: 0.25, minTier: 'beginner', category: 'isolation', animation: 'curl' , movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'continuous', materials: ['cable'], regressions: ['dumbbell_curl'], progressions: ['barbell_curl'] },
  { id: 'barbell_curl', primary: 'biceps', secondary: [], region: 'upper', implement: 'barbell', equipment: GYM, patterns: [], strengthRatio: 0.3, minTier: 'intermediate', category: 'isolation', animation: 'curl' , movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'continuous', regressions: ['dumbbell_curl', 'cable_curl'], mediaId: 'Barbell_Curl' },
  { id: 'triceps_pushdown', primary: 'triceps', secondary: [], region: 'upper', implement: 'cable', equipment: GYM, patterns: [], strengthRatio: 0.3, minTier: 'beginner', category: 'isolation', animation: 'pushdown' , movement: 'isolation', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'continuous', materials: ['cable'], regressions: ['bench_dip'], progressions: ['close_grip_bench_press', 'cable_overhead_triceps_extension'], mediaId: 'Triceps_Pushdown' },
  { id: 'overhead_triceps_extension', primary: 'triceps', secondary: [], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: ['overhead_press'], strengthRatio: 0.15, minTier: 'beginner', category: 'isolation', animation: 'overhead_extension' , movement: 'isolation', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '3010', breathing: 'continuous', regressions: ['triceps_pushdown'], progressions: ['cable_overhead_triceps_extension'] },
  { id: 'bench_dip', primary: 'triceps', secondary: ['chest'], region: 'upper', implement: 'bodyweight', equipment: ALL, patterns: ['loaded_wrist_extension'], strengthRatio: 0, minTier: 'beginner', category: 'accessory', animation: 'dip' , movement: 'vertical_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2010', breathing: 'exhale_effort', materials: ['bench'], regressions: ['incline_push_up'], progressions: ['diamond_push_up', 'dip'], mediaId: 'Bench_Dips' },
  { id: 'skull_crusher', primary: 'triceps', secondary: [], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.12, minTier: 'intermediate', category: 'isolation', animation: 'skull_crusher' , movement: 'isolation', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '3010', breathing: 'continuous', materials: ['bench'], regressions: ['triceps_pushdown'], progressions: ['close_grip_bench_press'], mediaId: 'EZ-Bar_Skullcrusher' },

  // ------------------------------------------------------------- core --
  { id: 'plank', primary: 'abs', secondary: [], region: 'core', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'core', animation: 'plank' , movement: 'anti_extension', force: 'static', plane: 'sagittal', purpose: 'stabilise', type: 'training', sfr: 'high', tempo: 'hold', breathing: 'slow', regressions: ['dead_bug'], progressions: ['ab_wheel_rollout', 'copenhagen_plank'], mediaId: 'Plank' },
  { id: 'side_plank', primary: 'abs', secondary: [], region: 'core', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'core', animation: 'side_plank', unilateral: true , movement: 'anti_lateral_flexion', force: 'static', plane: 'frontal', purpose: 'stabilise', type: 'training', sfr: 'high', tempo: 'hold', breathing: 'slow', regressions: ['dead_bug'], progressions: ['copenhagen_plank', 'suitcase_carry'], mediaId: 'Side_Bridge' },
  { id: 'dead_bug', primary: 'abs', secondary: [], region: 'core', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'core', animation: 'dead_bug' , movement: 'anti_extension', force: 'static', plane: 'sagittal', purpose: 'stabilise', type: 'training', sfr: 'high', tempo: '3010', breathing: 'slow', regressions: ['cat_cow'], progressions: ['plank', 'bird_dog'], mediaId: 'Dead_Bug' },
  { id: 'hanging_knee_raise', primary: 'abs', secondary: [], region: 'core', implement: 'bodyweight', equipment: GYM, patterns: ['deep_hip_flexion'], strengthRatio: 0, minTier: 'intermediate', category: 'core', animation: 'knee_raise' , movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2011', breathing: 'exhale_effort', materials: ['bar'], regressions: ['reverse_crunch', 'dead_bug'], progressions: ['hanging_leg_raise'] },
  { id: 'cable_crunch', primary: 'abs', secondary: [], region: 'core', implement: 'cable', equipment: GYM, patterns: [], strengthRatio: 0.3, minTier: 'beginner', category: 'core', animation: 'kneeling_crunch' , movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['cable'], regressions: ['bicycle_crunch'], progressions: ['ab_wheel_rollout'], mediaId: 'Cable_Crunch' },
  { id: 'pallof_press', primary: 'abs', secondary: [], region: 'core', implement: 'cable', equipment: GYM, patterns: [], strengthRatio: 0.15, minTier: 'beginner', category: 'core', animation: 'pallof', unilateral: true , movement: 'anti_rotation', force: 'static', plane: 'transverse', purpose: 'stabilise', type: 'training', sfr: 'high', tempo: '2020', breathing: 'slow', materials: ['cable'], regressions: ['side_plank'], progressions: ['russian_twist'], mediaId: 'Pallof_Press' },
  { id: 'bicycle_crunch', primary: 'abs', secondary: [], region: 'core', implement: 'bodyweight', equipment: ALL, patterns: ['neck_loading'], strengthRatio: 0, minTier: 'beginner', category: 'core', animation: 'bicycle' , movement: 'rotation', force: 'pull', plane: 'transverse', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'continuous', regressions: ['dead_bug'], progressions: ['russian_twist', 'hanging_knee_raise'], mediaId: 'Air_Bike' },

  // ----------------------------------------------------- conditioning --
  { id: 'burpee', primary: 'quads', secondary: ['chest', 'abs'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: ['loaded_wrist_extension', 'deep_knee_flexion'], strengthRatio: 0, minTier: 'beginner', category: 'conditioning', animation: 'burpee' , movement: 'gait', force: 'push', plane: 'multi', purpose: 'cardio', type: 'training', sfr: 'low', tempo: 'X', breathing: 'continuous', regressions: ['jumping_jack', 'mountain_climber'] },
  { id: 'jump_squat', primary: 'quads', secondary: ['glutes', 'calves'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: ['deep_knee_flexion'], strengthRatio: 0, minTier: 'beginner', category: 'conditioning', animation: 'jump' , movement: 'squat', force: 'push', plane: 'sagittal', purpose: 'cardio', type: 'training', sfr: 'moderate', tempo: 'X', breathing: 'continuous', regressions: ['bodyweight_squat'], progressions: ['box_jump'], mediaId: 'Freehand_Jump_Squat' },
  { id: 'mountain_climber', primary: 'abs', secondary: ['quads'], region: 'core', implement: 'bodyweight', equipment: ALL, patterns: ['loaded_wrist_extension', 'deep_hip_flexion'], strengthRatio: 0, minTier: 'beginner', category: 'conditioning', animation: 'mountain_climber' , movement: 'gait', force: 'push', plane: 'sagittal', purpose: 'cardio', type: 'training', sfr: 'moderate', tempo: 'X', breathing: 'continuous', regressions: ['plank'], progressions: ['burpee'], mediaId: 'Mountain_Climbers' },
  { id: 'jumping_jack', primary: 'calves', secondary: ['shoulders'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'conditioning', animation: 'jumping_jack' , movement: 'gait', force: 'push', plane: 'frontal', purpose: 'cardio', type: 'warmup', sfr: 'high', tempo: 'X', breathing: 'continuous', progressions: ['burpee'] },
  { id: 'farmers_carry', primary: 'abs', secondary: ['back', 'shoulders'], region: 'core', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.4, minTier: 'beginner', category: 'conditioning', animation: 'carry' , movement: 'carry', force: 'static', plane: 'sagittal', purpose: 'stabilise', type: 'training', sfr: 'high', tempo: 'hold', breathing: 'continuous', regressions: ['suitcase_carry'], mediaId: 'Farmers_Walk' },
  { id: 'dumbbell_swing', primary: 'glutes', secondary: ['hamstrings', 'back'], region: 'lower', implement: 'dumbbell', equipment: GYM_DB, patterns: ['loaded_hip_hinge'], strengthRatio: 0.25, minTier: 'beginner', category: 'conditioning', animation: 'swing' , movement: 'hinge', force: 'pull', plane: 'sagittal', purpose: 'cardio', type: 'training', sfr: 'moderate', tempo: 'X', breathing: 'exhale_effort', regressions: ['glute_bridge', 'dumbbell_rdl'], progressions: ['kettlebell_swing'] },
  { id: 'bike_intervals', primary: 'quads', secondary: ['calves'], region: 'lower', implement: 'machine', equipment: GYM, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'conditioning', machineId: 'bike', animation: 'bike' , movement: 'gait', force: 'push', plane: 'sagittal', purpose: 'cardio', type: 'training', sfr: 'high', tempo: 'X', breathing: 'continuous', materials: ['machine'] },
  { id: 'rower_intervals', primary: 'back', secondary: ['quads', 'glutes'], region: 'core', implement: 'machine', equipment: GYM, patterns: ['loaded_hip_hinge'], strengthRatio: 0, minTier: 'beginner', category: 'conditioning', machineId: 'rower', animation: 'rower' , movement: 'horizontal_pull', force: 'pull', plane: 'sagittal', purpose: 'cardio', type: 'training', sfr: 'high', tempo: 'X', breathing: 'continuous', materials: ['machine'] },
  // ------------------------------------------------------------- power --
  { id: 'box_jump', primary: 'quads', secondary: ['glutes', 'calves'], region: 'lower', implement: 'bodyweight', equipment: GYM_DB, patterns: ['deep_knee_flexion'], strengthRatio: 0, minTier: 'beginner', category: 'power', animation: 'jump' , movement: 'squat', force: 'push', plane: 'sagittal', purpose: 'nervous_system', type: 'training', sfr: 'moderate', tempo: 'X', breathing: 'exhale_effort', materials: ['box'], regressions: ['jump_squat'], progressions: ['broad_jump'], mediaId: 'Front_Box_Jump' },
  { id: 'broad_jump', primary: 'glutes', secondary: ['quads', 'hamstrings'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: ['deep_knee_flexion'], strengthRatio: 0, minTier: 'beginner', category: 'power', animation: 'jump' , movement: 'hinge', force: 'push', plane: 'sagittal', purpose: 'nervous_system', type: 'training', sfr: 'moderate', tempo: 'X', breathing: 'exhale_effort', regressions: ['jump_squat', 'box_jump'] },
  { id: 'push_press', primary: 'shoulders', secondary: ['triceps', 'quads'], region: 'upper', implement: 'barbell', equipment: GYM, patterns: ['overhead_press', 'spinal_loading'], strengthRatio: 0.6, minTier: 'intermediate', category: 'power', animation: 'vertical_push' , movement: 'vertical_push', force: 'push', plane: 'sagittal', purpose: 'nervous_system', type: 'training', sfr: 'moderate', tempo: 'X', breathing: 'brace', regressions: ['dumbbell_push_press', 'overhead_press'], mediaId: 'Push_Press' },
  { id: 'dumbbell_push_press', primary: 'shoulders', secondary: ['triceps', 'quads'], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: ['overhead_press'], strengthRatio: 0.2, minTier: 'beginner', category: 'power', animation: 'vertical_push' , movement: 'vertical_push', force: 'push', plane: 'sagittal', purpose: 'nervous_system', type: 'training', sfr: 'high', tempo: 'X', breathing: 'exhale_effort', regressions: ['dumbbell_shoulder_press'], progressions: ['push_press'] },
  { id: 'kettlebell_swing', primary: 'glutes', secondary: ['hamstrings', 'back'], region: 'lower', implement: 'dumbbell', equipment: GYM_DB, patterns: ['loaded_hip_hinge'], strengthRatio: 0.3, minTier: 'beginner', category: 'power', animation: 'swing' , movement: 'hinge', force: 'pull', plane: 'sagittal', purpose: 'nervous_system', type: 'training', sfr: 'high', tempo: 'X', breathing: 'exhale_effort', materials: ['kettlebell'], regressions: ['dumbbell_swing', 'dumbbell_rdl'], mediaId: 'One-Arm_Kettlebell_Swings' },
  { id: 'medicine_ball_slam', primary: 'abs', secondary: ['back', 'shoulders'], region: 'core', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.1, minTier: 'beginner', category: 'power', animation: 'overhead_extension' , movement: 'anti_extension', force: 'push', plane: 'sagittal', purpose: 'nervous_system', type: 'training', sfr: 'high', tempo: 'X', breathing: 'exhale_effort', materials: ['medicine_ball'], regressions: ['cable_crunch'], mediaId: 'One-Arm_Medicine_Ball_Slam' },
  // ---------------------------------------------------------- mobility --
  { id: 'hip_flexor_stretch', primary: 'quads', secondary: ['glutes'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'mobility', animation: 'lunge', unilateral: true, timed: true , movement: 'lunge', force: 'static', plane: 'sagittal', purpose: 'mobilise', type: 'stretch', sfr: 'high', tempo: 'hold', breathing: 'slow', mediaId: 'Kneeling_Hip_Flexor' },
  { id: 'worlds_greatest_stretch', primary: 'hamstrings', secondary: ['glutes', 'back'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'mobility', animation: 'lunge', unilateral: true, timed: true , movement: 'lunge', force: 'static', plane: 'multi', purpose: 'mobilise', type: 'warmup', sfr: 'high', tempo: 'hold', breathing: 'slow', regressions: ['hip_flexor_stretch'] },
  { id: 'ninety_ninety_hip', primary: 'glutes', secondary: [], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'mobility', animation: 'kneeling_crunch', unilateral: true, timed: true , movement: 'rotation', force: 'static', plane: 'transverse', purpose: 'mobilise', type: 'stretch', sfr: 'high', tempo: 'hold', breathing: 'slow' },
  { id: 'thoracic_rotation', primary: 'back', secondary: ['shoulders'], region: 'upper', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'mobility', animation: 'side_plank', unilateral: true, timed: true , movement: 'rotation', force: 'static', plane: 'transverse', purpose: 'mobilise', type: 'warmup', sfr: 'high', tempo: 'hold', breathing: 'slow', regressions: ['cat_cow'] },
  { id: 'cat_cow', primary: 'back', secondary: ['abs'], region: 'core', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'mobility', animation: 'superman', timed: true , movement: 'anti_extension', force: 'static', plane: 'sagittal', purpose: 'mobilise', type: 'warmup', sfr: 'high', tempo: 'hold', breathing: 'slow', progressions: ['dead_bug'], mediaId: 'Cat_Stretch' },
  { id: 'shoulder_dislocate', primary: 'shoulders', secondary: ['chest'], region: 'upper', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'mobility', animation: 'overhead_extension', timed: true , movement: 'vertical_push', force: 'static', plane: 'sagittal', purpose: 'mobilise', type: 'warmup', sfr: 'high', tempo: 'hold', breathing: 'slow', materials: ['band'], regressions: ['wall_slide'], mediaId: 'Shoulder_Circles' },
  { id: 'wall_slide', primary: 'shoulders', secondary: ['back'], region: 'upper', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'mobility', animation: 'vertical_push', timed: true , movement: 'vertical_push', force: 'static', plane: 'frontal', purpose: 'mobilise', type: 'rehab', sfr: 'high', tempo: 'hold', breathing: 'slow', progressions: ['pike_push_up', 'shoulder_dislocate'] },
  { id: 'calf_stretch', primary: 'calves', secondary: [], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'mobility', animation: 'calf_raise', unilateral: true, timed: true , movement: 'isolation', force: 'static', plane: 'sagittal', purpose: 'mobilise', type: 'stretch', sfr: 'high', tempo: 'hold', breathing: 'slow', materials: ['box'], progressions: ['bodyweight_calf_raise'], mediaId: 'Calf_Stretch_Hands_Against_Wall' },
  { id: 'deep_squat_hold', primary: 'quads', secondary: ['glutes', 'abs'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: ['deep_knee_flexion'], strengthRatio: 0, minTier: 'beginner', category: 'mobility', animation: 'squat', timed: true , movement: 'squat', force: 'static', plane: 'sagittal', purpose: 'mobilise', type: 'warmup', sfr: 'high', tempo: 'hold', breathing: 'slow', progressions: ['bodyweight_squat'] },
  { id: 'glute_bridge_hold', primary: 'glutes', secondary: ['hamstrings'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'mobility', animation: 'bridge', timed: true , movement: 'hinge', force: 'static', plane: 'sagittal', purpose: 'mobilise', type: 'rehab', sfr: 'high', tempo: 'hold', breathing: 'slow', progressions: ['glute_bridge'] },

  // ------------------------------------------------ phase 2 additions --
  { id: 'split_squat', primary: 'quads', secondary: ['glutes'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: ['loaded_lunge', 'deep_knee_flexion'], strengthRatio: 0, minTier: 'beginner', category: 'accessory', animation: 'split_squat', unilateral: true, movement: 'lunge', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '3010', breathing: 'exhale_effort', regressions: ['reverse_lunge'], progressions: ['bulgarian_split_squat'], mediaId: 'Split_Squats' },
  { id: 'pistol_squat', primary: 'quads', secondary: ['glutes', 'abs'], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: ['deep_knee_flexion', 'loaded_lunge'], strengthRatio: 0, minTier: 'advanced', category: 'compound', animation: 'squat', unilateral: true, movement: 'squat', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'low', tempo: '3010', breathing: 'exhale_effort', materials: ['box'], regressions: ['bulgarian_split_squat', 'bodyweight_squat'] },
  { id: 'sissy_squat', primary: 'quads', secondary: [], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: ['deep_knee_flexion', 'knee_extension_loaded'], strengthRatio: 0, minTier: 'advanced', category: 'isolation', animation: 'squat', movement: 'isolation', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '3010', breathing: 'exhale_effort', regressions: ['leg_extension', 'bodyweight_squat'] },
  { id: 'trap_bar_deadlift', primary: 'hamstrings', secondary: ['glutes', 'quads', 'back'], region: 'lower', implement: 'barbell', equipment: GYM, patterns: ['loaded_hip_hinge', 'spinal_loading'], strengthRatio: 1.3, minTier: 'intermediate', category: 'compound', animation: 'deadlift', movement: 'hinge', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2010', breathing: 'brace', regressions: ['dumbbell_rdl', 'romanian_deadlift'], progressions: ['conventional_deadlift'], mediaId: 'Trap_Bar_Deadlift' },
  { id: 'sumo_deadlift', primary: 'glutes', secondary: ['hamstrings', 'quads', 'back'], region: 'lower', implement: 'barbell', equipment: GYM, patterns: ['loaded_hip_hinge', 'spinal_loading'], strengthRatio: 1.2, minTier: 'intermediate', bigLift: true, category: 'compound', animation: 'deadlift', movement: 'hinge', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2010', breathing: 'brace', regressions: ['trap_bar_deadlift', 'romanian_deadlift'], mediaId: 'Sumo_Deadlift' },
  { id: 'good_morning', primary: 'hamstrings', secondary: ['glutes', 'back'], region: 'lower', implement: 'barbell', equipment: GYM, patterns: ['loaded_hip_hinge', 'spinal_loading'], strengthRatio: 0.4, minTier: 'advanced', category: 'accessory', animation: 'hinge', movement: 'hinge', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'low', tempo: '3010', breathing: 'brace', regressions: ['romanian_deadlift', 'back_extension'], mediaId: 'Good_Morning' },
  { id: 'cable_pull_through', primary: 'glutes', secondary: ['hamstrings'], region: 'lower', implement: 'cable', equipment: GYM, patterns: ['loaded_hip_hinge'], strengthRatio: 0.4, minTier: 'beginner', category: 'accessory', animation: 'hinge', movement: 'hinge', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['cable'], regressions: ['glute_bridge'], progressions: ['dumbbell_rdl', 'romanian_deadlift'], mediaId: 'Band_Good_Morning_Pull_Through' },
  { id: 'single_leg_rdl', primary: 'hamstrings', secondary: ['glutes'], region: 'lower', implement: 'dumbbell', equipment: GYM_DB, patterns: ['loaded_hip_hinge'], strengthRatio: 0.15, minTier: 'intermediate', category: 'accessory', animation: 'hinge', unilateral: true, movement: 'hinge', force: 'pull', plane: 'sagittal', purpose: 'stabilise', type: 'training', sfr: 'high', tempo: '3010', breathing: 'brace', regressions: ['dumbbell_rdl'], progressions: ['romanian_deadlift'] },
  { id: 'seated_leg_curl', primary: 'hamstrings', secondary: [], region: 'lower', implement: 'machine', equipment: GYM, patterns: [], strengthRatio: 0.45, minTier: 'beginner', category: 'isolation', machineId: 'leg_curl', animation: 'leg_curl', movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['machine'], progressions: ['nordic_curl'], mediaId: 'Seated_Leg_Curl' },
  { id: 'glute_ham_raise', primary: 'hamstrings', secondary: ['glutes', 'back'], region: 'lower', implement: 'bodyweight', equipment: GYM, patterns: ['loaded_hip_hinge'], strengthRatio: 0, minTier: 'advanced', category: 'accessory', machineId: 'ghd', animation: 'nordic', movement: 'hinge', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'low', tempo: '4010', breathing: 'exhale_effort', materials: ['machine'], regressions: ['nordic_curl', 'leg_curl'], mediaId: 'Glute_Ham_Raise' },
  { id: 'back_extension', primary: 'back', secondary: ['glutes', 'hamstrings'], region: 'core', implement: 'bodyweight', equipment: GYM, patterns: ['loaded_hip_hinge'], strengthRatio: 0, minTier: 'beginner', category: 'accessory', machineId: 'hyperextension_bench', animation: 'superman', movement: 'hinge', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['bench'], regressions: ['superman', 'bird_dog'], progressions: ['good_morning', 'romanian_deadlift'], mediaId: 'Hyperextensions_Back_Extensions' },
  { id: 'seated_calf_raise', primary: 'calves', secondary: [], region: 'lower', implement: 'machine', equipment: GYM, patterns: [], strengthRatio: 0.8, minTier: 'beginner', category: 'isolation', machineId: 'seated_calf', animation: 'calf_raise', movement: 'isolation', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2012', breathing: 'continuous', materials: ['machine'], regressions: ['bodyweight_calf_raise'], mediaId: 'Seated_Calf_Raise' },
  { id: 'single_leg_calf_raise', primary: 'calves', secondary: [], region: 'lower', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'isolation', animation: 'calf_raise', unilateral: true, movement: 'isolation', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2012', breathing: 'continuous', materials: ['box'], regressions: ['bodyweight_calf_raise'], progressions: ['dumbbell_calf_raise'] },
  { id: 'incline_bench_press', primary: 'chest', secondary: ['shoulders', 'triceps'], region: 'upper', implement: 'barbell', equipment: GYM, patterns: [], strengthRatio: 0.6, minTier: 'intermediate', category: 'compound', animation: 'incline_press', movement: 'horizontal_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2010', breathing: 'brace', materials: ['bench'], regressions: ['incline_dumbbell_press'], mediaId: 'Barbell_Incline_Bench_Press_-_Medium_Grip' },
  { id: 'close_grip_bench_press', primary: 'chest', secondary: ['triceps', 'shoulders'], region: 'upper', implement: 'barbell', equipment: GYM, patterns: [], strengthRatio: 0.65, minTier: 'intermediate', category: 'compound', animation: 'horizontal_push', movement: 'horizontal_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2010', breathing: 'brace', materials: ['bench'], regressions: ['diamond_push_up', 'triceps_pushdown'], mediaId: 'Close-Grip_Barbell_Bench_Press' },
  { id: 'dip', primary: 'chest', secondary: ['triceps', 'shoulders'], region: 'upper', implement: 'bodyweight', equipment: GYM, patterns: [], strengthRatio: 0, minTier: 'intermediate', category: 'compound', animation: 'dip', movement: 'vertical_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2010', breathing: 'exhale_effort', materials: ['bar'], regressions: ['bench_dip', 'push_up'], mediaId: 'Dips_-_Chest_Version' },
  { id: 'incline_push_up', primary: 'chest', secondary: ['triceps'], region: 'upper', implement: 'bodyweight', equipment: ALL, patterns: ['loaded_wrist_extension'], strengthRatio: 0, minTier: 'beginner', category: 'compound', animation: 'push_up', movement: 'horizontal_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', materials: ['bench'], progressions: ['push_up'], mediaId: 'Incline_Push-Up' },
  { id: 'decline_push_up', primary: 'chest', secondary: ['shoulders', 'triceps'], region: 'upper', implement: 'bodyweight', equipment: ALL, patterns: ['loaded_wrist_extension'], strengthRatio: 0, minTier: 'intermediate', category: 'compound', animation: 'push_up', movement: 'horizontal_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', materials: ['bench'], regressions: ['push_up'], progressions: ['dip'], mediaId: 'Decline_Push-Up' },
  { id: 'diamond_push_up', primary: 'triceps', secondary: ['chest'], region: 'upper', implement: 'bodyweight', equipment: ALL, patterns: ['loaded_wrist_extension'], strengthRatio: 0, minTier: 'intermediate', category: 'accessory', animation: 'push_up', movement: 'horizontal_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', regressions: ['push_up', 'bench_dip'], progressions: ['close_grip_bench_press'] },
  { id: 'machine_fly', primary: 'chest', secondary: [], region: 'upper', implement: 'machine', equipment: GYM, patterns: [], strengthRatio: 0.4, minTier: 'beginner', category: 'isolation', machineId: 'pec_deck', animation: 'fly', movement: 'isolation', force: 'push', plane: 'transverse', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['machine'], regressions: ['dumbbell_fly'], progressions: ['cable_fly'], mediaId: 'Butterfly' },
  { id: 'arnold_press', primary: 'shoulders', secondary: ['triceps', 'chest'], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: ['overhead_press'], strengthRatio: 0.18, minTier: 'intermediate', category: 'compound', animation: 'seated_press', movement: 'vertical_push', force: 'push', plane: 'multi', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', materials: ['bench'], regressions: ['dumbbell_shoulder_press'], mediaId: 'Arnold_Dumbbell_Press' },
  { id: 'landmine_press', primary: 'shoulders', secondary: ['chest', 'triceps'], region: 'upper', implement: 'barbell', equipment: GYM, patterns: [], strengthRatio: 0.3, minTier: 'beginner', category: 'compound', animation: 'incline_press', unilateral: true, movement: 'vertical_push', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'rehab', sfr: 'high', tempo: '2010', breathing: 'exhale_effort', regressions: ['pike_push_up'], progressions: ['overhead_press'] },
  { id: 'cable_lateral_raise', primary: 'shoulders', secondary: [], region: 'upper', implement: 'cable', equipment: GYM, patterns: [], strengthRatio: 0.06, minTier: 'beginner', category: 'isolation', animation: 'lateral_raise', unilateral: true, movement: 'isolation', force: 'pull', plane: 'frontal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'continuous', materials: ['cable'], regressions: ['lateral_raise'] },
  { id: 'band_pull_apart', primary: 'shoulders', secondary: ['back'], region: 'upper', implement: 'bodyweight', equipment: GYM_DB, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'isolation', animation: 'rear_delt_fly', movement: 'horizontal_pull', force: 'pull', plane: 'transverse', purpose: 'stabilise', type: 'warmup', sfr: 'high', tempo: '2011', breathing: 'continuous', materials: ['band'], progressions: ['face_pull', 'rear_delt_fly'], mediaId: 'Band_Pull_Apart' },
  { id: 'y_raise', primary: 'shoulders', secondary: ['back'], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.04, minTier: 'beginner', category: 'isolation', animation: 'lateral_raise', movement: 'isolation', force: 'pull', plane: 'frontal', purpose: 'stabilise', type: 'rehab', sfr: 'high', tempo: '2011', breathing: 'continuous', materials: ['bench'], regressions: ['wall_slide'], progressions: ['lateral_raise'] },
  { id: 'chin_up', primary: 'back', secondary: ['biceps'], region: 'upper', implement: 'bodyweight', equipment: GYM, patterns: [], strengthRatio: 0, minTier: 'intermediate', category: 'compound', animation: 'vertical_pull', movement: 'vertical_pull', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2011', breathing: 'exhale_effort', materials: ['bar'], regressions: ['assisted_pull_up', 'lat_pulldown'], progressions: ['pull_up'], mediaId: 'Chin-Up' },
  { id: 'assisted_pull_up', primary: 'back', secondary: ['biceps'], region: 'upper', implement: 'machine', equipment: GYM, patterns: [], strengthRatio: 0.5, minTier: 'beginner', category: 'compound', machineId: 'assisted_pullup', animation: 'vertical_pull', movement: 'vertical_pull', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['machine'], regressions: ['lat_pulldown'], progressions: ['chin_up', 'pull_up'], mediaId: 'Band_Assisted_Pull-Up' },
  { id: 'pendlay_row', primary: 'back', secondary: ['biceps', 'hamstrings'], region: 'upper', implement: 'barbell', equipment: GYM, patterns: ['loaded_hip_hinge', 'spinal_loading'], strengthRatio: 0.6, minTier: 'advanced', category: 'compound', animation: 'horizontal_pull', movement: 'horizontal_pull', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'low', tempo: 'X010', breathing: 'brace', regressions: ['barbell_row', 'chest_supported_row'] },
  { id: 't_bar_row', primary: 'back', secondary: ['biceps'], region: 'upper', implement: 'machine', equipment: GYM, patterns: ['loaded_hip_hinge'], strengthRatio: 0.7, minTier: 'intermediate', category: 'compound', machineId: 't_bar', animation: 'horizontal_pull', movement: 'horizontal_pull', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2011', breathing: 'brace', materials: ['machine'], regressions: ['chest_supported_row', 'seated_cable_row'], progressions: ['barbell_row'], mediaId: 'T-Bar_Row_with_Handle' },
  { id: 'suspension_row', primary: 'back', secondary: ['biceps'], region: 'upper', implement: 'bodyweight', equipment: GYM_DB, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'compound', animation: 'inverted_row', movement: 'horizontal_pull', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['suspension'], regressions: ['band_pull_apart'], progressions: ['inverted_row', 'dumbbell_row'], mediaId: 'Inverted_Row_with_Straps' },
  { id: 'straight_arm_pulldown', primary: 'back', secondary: [], region: 'upper', implement: 'cable', equipment: GYM, patterns: [], strengthRatio: 0.25, minTier: 'beginner', category: 'isolation', animation: 'lat_pulldown', movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', materials: ['cable'], progressions: ['lat_pulldown'], mediaId: 'Straight-Arm_Pulldown' },
  { id: 'bird_dog', primary: 'back', secondary: ['abs', 'glutes'], region: 'core', implement: 'bodyweight', equipment: ALL, patterns: [], strengthRatio: 0, minTier: 'beginner', category: 'core', animation: 'dead_bug', unilateral: true, movement: 'anti_rotation', force: 'static', plane: 'multi', purpose: 'stabilise', type: 'rehab', sfr: 'high', tempo: '2020', breathing: 'slow', regressions: ['cat_cow'], progressions: ['superman', 'plank'] },
  { id: 'preacher_curl', primary: 'biceps', secondary: [], region: 'upper', implement: 'barbell', equipment: GYM, patterns: [], strengthRatio: 0.2, minTier: 'beginner', category: 'isolation', machineId: 'preacher_bench', animation: 'curl', movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '3010', breathing: 'continuous', materials: ['bench'], regressions: ['dumbbell_curl'], mediaId: 'Preacher_Curl' },
  { id: 'incline_dumbbell_curl', primary: 'biceps', secondary: [], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.1, minTier: 'intermediate', category: 'isolation', animation: 'curl', movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '3010', breathing: 'continuous', materials: ['bench'], regressions: ['dumbbell_curl'], mediaId: 'Incline_Dumbbell_Curl' },
  { id: 'concentration_curl', primary: 'biceps', secondary: [], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.1, minTier: 'beginner', category: 'isolation', animation: 'curl', unilateral: true, movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'continuous', materials: ['bench'], regressions: ['dumbbell_curl'], mediaId: 'Concentration_Curls' },
  { id: 'cable_overhead_triceps_extension', primary: 'triceps', secondary: [], region: 'upper', implement: 'cable', equipment: GYM, patterns: ['overhead_press'], strengthRatio: 0.25, minTier: 'beginner', category: 'isolation', animation: 'overhead_extension', movement: 'isolation', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '3010', breathing: 'continuous', materials: ['cable'], regressions: ['triceps_pushdown'], mediaId: 'Triceps_Overhead_Extension_with_Rope' },
  { id: 'triceps_kickback', primary: 'triceps', secondary: [], region: 'upper', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.06, minTier: 'beginner', category: 'isolation', animation: 'pushdown', unilateral: true, movement: 'isolation', force: 'push', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'continuous', materials: ['bench'], progressions: ['skull_crusher'], mediaId: 'Tricep_Dumbbell_Kickback' },
  { id: 'ab_wheel_rollout', primary: 'abs', secondary: ['back'], region: 'core', implement: 'bodyweight', equipment: GYM_DB, patterns: ['spinal_loading'], strengthRatio: 0, minTier: 'intermediate', category: 'core', animation: 'plank', movement: 'anti_extension', force: 'static', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '3010', breathing: 'brace', materials: ['other'], regressions: ['plank', 'dead_bug'], mediaId: 'Ab_Roller' },
  { id: 'hanging_leg_raise', primary: 'abs', secondary: [], region: 'core', implement: 'bodyweight', equipment: GYM, patterns: ['deep_hip_flexion'], strengthRatio: 0, minTier: 'advanced', category: 'core', animation: 'knee_raise', movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'moderate', tempo: '2011', breathing: 'exhale_effort', materials: ['bar'], regressions: ['hanging_knee_raise', 'reverse_crunch'], mediaId: 'Hanging_Leg_Raise' },
  { id: 'copenhagen_plank', primary: 'abs', secondary: ['glutes'], region: 'core', implement: 'bodyweight', equipment: GYM_DB, patterns: [], strengthRatio: 0, minTier: 'intermediate', category: 'core', animation: 'side_plank', unilateral: true, timed: true, movement: 'anti_lateral_flexion', force: 'static', plane: 'frontal', purpose: 'stabilise', type: 'rehab', sfr: 'moderate', tempo: 'hold', breathing: 'slow', materials: ['bench'], regressions: ['side_plank'] },
  { id: 'suitcase_carry', primary: 'abs', secondary: ['back', 'shoulders'], region: 'core', implement: 'dumbbell', equipment: GYM_DB, patterns: [], strengthRatio: 0.35, minTier: 'beginner', category: 'core', animation: 'carry', unilateral: true, timed: true, movement: 'carry', force: 'static', plane: 'frontal', purpose: 'stabilise', type: 'training', sfr: 'high', tempo: 'hold', breathing: 'continuous', regressions: ['side_plank'], progressions: ['farmers_carry'] },
  { id: 'russian_twist', primary: 'abs', secondary: [], region: 'core', implement: 'bodyweight', equipment: ALL, patterns: ['spinal_loading'], strengthRatio: 0, minTier: 'beginner', category: 'core', animation: 'bicycle', movement: 'rotation', force: 'pull', plane: 'transverse', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2010', breathing: 'continuous', regressions: ['pallof_press', 'dead_bug'], mediaId: 'Russian_Twist' },
  { id: 'reverse_crunch', primary: 'abs', secondary: [], region: 'core', implement: 'bodyweight', equipment: ALL, patterns: ['deep_hip_flexion'], strengthRatio: 0, minTier: 'beginner', category: 'core', animation: 'crunch', movement: 'isolation', force: 'pull', plane: 'sagittal', purpose: 'strengthen', type: 'training', sfr: 'high', tempo: '2011', breathing: 'exhale_effort', regressions: ['dead_bug'], progressions: ['hanging_knee_raise'], mediaId: 'Reverse_Crunch' },
]

const BY_ID: ReadonlyMap<string, ExerciseDefinition> = new Map(EXERCISES.map((e) => [e.id, e]))

export function getExercise(id: string): ExerciseDefinition {
  const exercise = BY_ID.get(id)
  if (!exercise) throw new RangeError(`unknown exercise: ${id}`)
  return exercise
}

export function findExercise(id: string): ExerciseDefinition | undefined {
  return BY_ID.get(id)
}

export const EXERCISE_IDS: readonly string[] = EXERCISES.map((e) => e.id)

/** Every distinct machine id, for the "machines unavailable" questionnaire step. */
export const MACHINE_IDS: readonly string[] = [
  ...new Set(EXERCISES.flatMap((e) => (e.machineId ? [e.machineId] : []))),
]
