"""One-off: merges exercise names, cues and common mistakes into both message
catalogues. The JSON files are the source of truth once written; this script
exists so the two languages are authored side by side and cannot drift."""
import json, pathlib

# id: (en_name, es_name, [en cues], [es cues], [en mistakes], [es mistakes])
X = {
 'back_squat': ('Back squat','Sentadilla con barra',
   ['Brace your trunk before you descend','Push the floor away, knees tracking over toes'],
   ['Aprieta el tronco antes de bajar','Empuja el piso, con las rodillas siguiendo la línea de los pies'],
   ['Knees caving inward','Heels lifting off the floor'],
   ['Rodillas que se van hacia adentro','Talones que se despegan del piso']),
 'front_squat': ('Front squat','Sentadilla frontal',
   ['Elbows high, bar resting on the shoulders','Stay upright all the way down'],
   ['Codos altos, la barra descansa sobre los hombros','Mantente erguido durante toda la bajada'],
   ['Elbows dropping and the bar rolling forward','Rounding the upper back'],
   ['Codos que caen y la barra rueda hacia adelante','Redondear la espalda alta']),
 'goblet_squat': ('Goblet squat','Sentadilla goblet',
   ['Hold the weight against your chest','Sit down between your heels'],
   ['Sostén la pesa contra el pecho','Baja sentándote entre los talones'],
   ['Leaning forward as you go down','Only going halfway'],
   ['Inclinarte hacia adelante al bajar','Bajar solo hasta la mitad']),
 'leg_press': ('Leg press','Prensa de piernas',
   ['Lower until your thighs meet your torso','Keep your lower back on the pad'],
   ['Baja hasta que los muslos toquen el torso','Mantén la espalda baja pegada al respaldo'],
   ['Locking the knees at the top','Letting the hips roll off the seat'],
   ['Bloquear las rodillas arriba','Dejar que la cadera se despegue del asiento']),
 'hack_squat': ('Hack squat','Sentadilla hack',
   ['Shoulders under the pads, feet mid-platform','Control the descent, drive up through the whole foot'],
   ['Hombros bajo las almohadillas, pies al centro de la plataforma','Controla la bajada y sube empujando con todo el pie'],
   ['Bouncing out of the bottom','Heels rising'],
   ['Rebotar en el punto más bajo','Talones que se levantan']),
 'bulgarian_split_squat': ('Bulgarian split squat','Sentadilla búlgara',
   ['Rear foot on the bench, front foot a long stride ahead','Drop straight down, front shin near vertical'],
   ['Pie trasero en el banco, pie delantero un paso largo adelante','Baja en línea recta, la espinilla delantera casi vertical'],
   ['Standing too close to the bench','Pushing off the back foot'],
   ['Pararte muy cerca del banco','Impulsarte con el pie trasero']),
 'walking_lunge': ('Walking lunge','Zancada caminando',
   ['Long step, back knee toward the floor','Torso tall, drive through the front heel'],
   ['Paso largo, la rodilla trasera hacia el piso','Torso alto, empuja con el talón delantero'],
   ['Short steps that jam the front knee','Leaning forward'],
   ['Pasos cortos que fuerzan la rodilla delantera','Inclinarte hacia adelante']),
 'step_up': ('Step-up','Subida al cajón',
   ['Whole foot on the box','Push through the top leg, not the bottom one'],
   ['Todo el pie sobre el cajón','Empuja con la pierna de arriba, no con la de abajo'],
   ['Bouncing off the floor leg','Box too high for control'],
   ['Impulsarte con la pierna del piso','Cajón demasiado alto para controlarlo']),
 'bodyweight_squat': ('Bodyweight squat','Sentadilla sin peso',
   ['Arms forward for balance','Sit back and down, chest up'],
   ['Brazos al frente para equilibrar','Siéntate hacia atrás y abajo, con el pecho arriba'],
   ['Knees collapsing inward','Rushing the reps'],
   ['Rodillas que colapsan hacia adentro','Hacer las repeticiones a las carreras']),
 'reverse_lunge': ('Reverse lunge','Zancada hacia atrás',
   ['Step back and lower the rear knee','Front shin stays near vertical'],
   ['Da un paso atrás y baja la rodilla trasera','La espinilla delantera se queda casi vertical'],
   ['Leaning forward','Twisting the hips'],
   ['Inclinarte hacia adelante','Girar la cadera']),
 'leg_extension': ('Leg extension','Extensión de piernas',
   ['Pad just above the ankles','Pause for a second at the top'],
   ['Almohadilla justo encima de los tobillos','Haz una pausa de un segundo arriba'],
   ['Swinging the weight up','Lifting the hips off the seat'],
   ['Lanzar el peso hacia arriba','Despegar la cadera del asiento']),
 'conventional_deadlift': ('Deadlift','Peso muerto',
   ['Bar over mid-foot, shins to the bar','Push the floor away, keep the bar close'],
   ['Barra sobre el medio del pie, espinillas a la barra','Empuja el piso y mantén la barra pegada'],
   ['Rounding the lower back','Jerking the bar off the floor'],
   ['Redondear la espalda baja','Arrancar la barra del piso de un tirón']),
 'romanian_deadlift': ('Romanian deadlift','Peso muerto rumano',
   ['Soft knees, push the hips back','Lower until you feel the hamstrings, then stand'],
   ['Rodillas suaves, lleva la cadera hacia atrás','Baja hasta sentir los isquiotibiales y vuelve a subir'],
   ['Bending the knees into a squat','Bar drifting away from the legs'],
   ['Doblar las rodillas hasta convertirlo en sentadilla','La barra se aleja de las piernas']),
 'dumbbell_rdl': ('Dumbbell Romanian deadlift','Peso muerto rumano con mancuernas',
   ['Dumbbells brushing the thighs','Hinge at the hips, flat back'],
   ['Las mancuernas rozan los muslos','Bisagra en la cadera, espalda plana'],
   ['Rounding the back','Turning it into a squat'],
   ['Redondear la espalda','Convertirlo en sentadilla']),
 'leg_curl': ('Leg curl','Curl de piernas',
   ['Pad on the lower calves','Squeeze at the top, control the way back'],
   ['Almohadilla en la parte baja de las pantorrillas','Aprieta arriba y controla la vuelta'],
   ['Lifting the hips','Letting the weight drop'],
   ['Levantar la cadera','Dejar caer el peso']),
 'nordic_curl': ('Nordic curl','Curl nórdico',
   ['Hips straight, lower as slowly as you can','Catch yourself with your hands'],
   ['Cadera recta, baja lo más lento que puedas','Amortigua con las manos'],
   ['Breaking at the hips','Dropping the last half'],
   ['Doblar la cadera','Dejarte caer en la última mitad']),
 'hip_thrust': ('Hip thrust','Empuje de cadera',
   ['Shoulder blades on the bench, chin tucked','Drive up until the hips are level, squeeze'],
   ['Omóplatos sobre el banco, mentón recogido','Sube hasta que la cadera quede horizontal y aprieta'],
   ['Overarching the lower back at the top','Feet too far forward'],
   ['Arquear demasiado la espalda baja arriba','Pies demasiado adelante']),
 'dumbbell_hip_thrust': ('Dumbbell hip thrust','Empuje de cadera con mancuerna',
   ['Dumbbell across the hips','Pause at the top for a second'],
   ['Mancuerna sobre la cadera','Pausa de un segundo arriba'],
   ['Pushing through the toes','Rushing the reps'],
   ['Empujar con la punta de los pies','Ir a las carreras']),
 'glute_bridge': ('Glute bridge','Puente de glúteo',
   ['Heels close to the hips','Squeeze the glutes, not the lower back'],
   ['Talones cerca de la cadera','Aprieta los glúteos, no la espalda baja'],
   ['Arching the back','Not going all the way up'],
   ['Arquear la espalda','No subir del todo']),
 'cable_kickback': ('Cable kickback','Patada de glúteo en polea',
   ['Slight forward lean, hold the frame','Kick back and slightly up'],
   ['Ligera inclinación al frente, sujeta el marco','Patea hacia atrás y un poco arriba'],
   ['Swinging with momentum','Arching the lower back'],
   ['Balancear con impulso','Arquear la espalda baja']),
 'hip_abduction': ('Hip abduction','Abducción de cadera',
   ['Lean slightly forward','Pause at the widest point'],
   ['Inclínate un poco hacia adelante','Pausa en el punto más abierto'],
   ['Bouncing the pads together','Too much weight'],
   ['Rebotar las almohadillas','Demasiado peso']),
 'single_leg_glute_bridge': ('Single-leg glute bridge','Puente de glúteo a una pierna',
   ['Other knee to chest','Hips level as you rise'],
   ['La otra rodilla al pecho','Cadera nivelada al subir'],
   ['Hips tilting to one side','Pushing with the toes'],
   ['Cadera que se inclina a un lado','Empujar con los dedos del pie']),
 'standing_calf_raise': ('Standing calf raise','Elevación de talones de pie',
   ['Full stretch at the bottom','Pause at the top'],
   ['Estiramiento completo abajo','Pausa arriba'],
   ['Bouncing','Bending the knees'],
   ['Rebotar','Doblar las rodillas']),
 'dumbbell_calf_raise': ('Dumbbell calf raise','Elevación de talones con mancuernas',
   ['Toes on a step for range','Slow on the way down'],
   ['Puntas de los pies en un escalón para más recorrido','Lento en la bajada'],
   ['Half reps','Leaning on the wall too much'],
   ['Medias repeticiones','Apoyarte demasiado en la pared']),
 'bodyweight_calf_raise': ('Calf raise','Elevación de talones',
   ['Rise as high as you can','Lower slowly'],
   ['Sube lo más alto que puedas','Baja despacio'],
   ['Bouncing','Rushing'],
   ['Rebotar','Ir a las carreras']),
 'bench_press': ('Bench press','Press de banca',
   ['Shoulder blades pulled together, feet planted','Bar to the lower chest, press up and slightly back'],
   ['Omóplatos juntos, pies bien plantados','La barra a la parte baja del pecho, empuja arriba y un poco atrás'],
   ['Bouncing the bar off the chest','Flaring the elbows out wide'],
   ['Rebotar la barra en el pecho','Abrir demasiado los codos']),
 'dumbbell_bench_press': ('Dumbbell bench press','Press de banca con mancuernas',
   ['Elbows at about 45 degrees','Lower to chest level'],
   ['Codos a unos 45 grados','Baja hasta la altura del pecho'],
   ['Clanging the dumbbells at the top','Shortening the range'],
   ['Chocar las mancuernas arriba','Acortar el recorrido']),
 'incline_dumbbell_press': ('Incline dumbbell press','Press inclinado con mancuernas',
   ['Bench at 30 degrees','Lower to the upper chest'],
   ['Banco a 30 grados','Baja a la parte alta del pecho'],
   ['Bench too steep','Arching off the bench'],
   ['Banco demasiado empinado','Arquearte fuera del banco']),
 'chest_press_machine': ('Chest press machine','Press de pecho en máquina',
   ['Handles at chest height','Squeeze the chest at the end'],
   ['Agarres a la altura del pecho','Aprieta el pecho al final'],
   ['Shoulders rolling forward','Locking the elbows hard'],
   ['Hombros que ruedan hacia adelante','Bloquear los codos con fuerza']),
 'push_up': ('Push-up','Flexión de pecho',
   ['Body in one straight line','Chest to the floor, elbows tucked'],
   ['Cuerpo en una sola línea recta','Pecho al piso, codos pegados'],
   ['Hips sagging','Only going halfway'],
   ['Cadera que se hunde','Bajar solo hasta la mitad']),
 'cable_fly': ('Cable fly','Aperturas en polea',
   ['Slight bend in the elbows','Bring the hands together in front of the chest'],
   ['Codos ligeramente doblados','Junta las manos frente al pecho'],
   ['Turning it into a press','Too much weight'],
   ['Convertirlo en un press','Demasiado peso']),
 'dumbbell_fly': ('Dumbbell fly','Aperturas con mancuernas',
   ['Wide arc, elbows soft','Stop when you feel the stretch'],
   ['Arco amplio, codos suaves','Detente cuando sientas el estiramiento'],
   ['Going too deep','Bending the elbows into a press'],
   ['Bajar demasiado','Doblar los codos hasta hacer un press']),
 'overhead_press': ('Overhead press','Press militar',
   ['Bar at the collarbones, glutes tight','Press straight up, head through at the top'],
   ['Barra en las clavículas, glúteos apretados','Empuja recto arriba y pasa la cabeza al final'],
   ['Leaning back','Pressing forward around the face'],
   ['Inclinarte hacia atrás','Empujar hacia adelante rodeando la cara']),
 'dumbbell_shoulder_press': ('Dumbbell shoulder press','Press de hombros con mancuernas',
   ['Start at ear height','Press until the arms are straight'],
   ['Empieza a la altura de las orejas','Empuja hasta estirar los brazos'],
   ['Arching the lower back','Clanging the dumbbells'],
   ['Arquear la espalda baja','Chocar las mancuernas']),
 'machine_shoulder_press': ('Machine shoulder press','Press de hombros en máquina',
   ['Handles level with the shoulders','Control the way down'],
   ['Agarres al nivel de los hombros','Controla la bajada'],
   ['Shrugging the shoulders','Half reps'],
   ['Encoger los hombros','Medias repeticiones']),
 'pike_push_up': ('Pike push-up','Flexión en pica',
   ['Hips high, head toward the floor','Press back up to the start'],
   ['Cadera alta, cabeza hacia el piso','Empuja para volver al inicio'],
   ['Hips dropping','Elbows flaring'],
   ['Cadera que cae','Codos abiertos']),
 'lateral_raise': ('Lateral raise','Elevación lateral',
   ['Slight bend in the elbows','Raise to shoulder height, lead with the elbows'],
   ['Codos ligeramente doblados','Sube hasta la altura de los hombros, guiando con los codos'],
   ['Swinging the weight up','Shrugging'],
   ['Lanzar el peso con impulso','Encoger los hombros']),
 'face_pull': ('Face pull','Jalón a la cara',
   ['Rope at face height','Pull to the face, elbows high and wide'],
   ['Cuerda a la altura de la cara','Jala hacia la cara, codos altos y abiertos'],
   ['Too heavy','Elbows dropping'],
   ['Demasiado peso','Codos que caen']),
 'rear_delt_fly': ('Rear delt fly','Vuelo posterior',
   ['Hinge forward, flat back','Raise out to the sides'],
   ['Inclínate hacia adelante con la espalda plana','Sube hacia los lados'],
   ['Standing too upright','Swinging'],
   ['Pararte demasiado erguido','Balancear']),
 'barbell_row': ('Barbell row','Remo con barra',
   ['Hinge to about 45 degrees','Pull to the lower ribs, squeeze the back'],
   ['Inclínate a unos 45 grados','Jala hacia las costillas bajas y aprieta la espalda'],
   ['Standing up as you pull','Rounding the back'],
   ['Enderezarte al jalar','Redondear la espalda']),
 'dumbbell_row': ('Dumbbell row','Remo con mancuerna',
   ['Hand and knee on the bench','Pull to the hip, not the shoulder'],
   ['Mano y rodilla en el banco','Jala hacia la cadera, no hacia el hombro'],
   ['Twisting the torso','Yanking the weight'],
   ['Girar el torso','Jalar el peso de un tirón']),
 'chest_supported_row': ('Chest-supported row','Remo con apoyo de pecho',
   ['Chest stays on the pad','Squeeze the shoulder blades together'],
   ['El pecho se queda en la almohadilla','Junta los omóplatos'],
   ['Lifting the chest off','Shrugging'],
   ['Despegar el pecho','Encoger los hombros']),
 'seated_cable_row': ('Seated cable row','Remo sentado en polea',
   ['Sit tall, chest up','Pull to the stomach, elbows back'],
   ['Siéntate erguido, con el pecho arriba','Jala hacia el estómago, codos atrás'],
   ['Leaning back too far','Rounding forward at the start'],
   ['Inclinarte demasiado hacia atrás','Redondearte al inicio']),
 'lat_pulldown': ('Lat pulldown','Jalón al pecho',
   ['Grip a bit wider than the shoulders','Pull to the upper chest, elbows down'],
   ['Agarre un poco más ancho que los hombros','Jala al pecho alto, codos hacia abajo'],
   ['Leaning way back','Pulling behind the neck'],
   ['Inclinarte mucho hacia atrás','Jalar detrás del cuello']),
 'pull_up': ('Pull-up','Dominada',
   ['Start from a dead hang','Chin over the bar, control the descent'],
   ['Empieza colgando con los brazos estirados','Mentón sobre la barra y controla la bajada'],
   ['Kipping','Half reps'],
   ['Impulsarte con las piernas','Medias repeticiones']),
 'inverted_row': ('Inverted row','Remo invertido',
   ['Body straight, heels on the floor','Pull the chest to the bar'],
   ['Cuerpo recto, talones en el piso','Lleva el pecho a la barra'],
   ['Hips sagging','Short range'],
   ['Cadera que se hunde','Recorrido corto']),
 'superman': ('Superman','Superman',
   ['Lift arms and legs together','Hold for a second at the top'],
   ['Levanta brazos y piernas a la vez','Mantén un segundo arriba'],
   ['Jerking up','Holding your breath'],
   ['Subir de un tirón','Aguantar la respiración']),
 'dumbbell_curl': ('Dumbbell curl','Curl con mancuernas',
   ['Elbows pinned to the sides','Lower slowly'],
   ['Codos pegados a los costados','Baja despacio'],
   ['Swinging the body','Elbows drifting forward'],
   ['Balancear el cuerpo','Codos que se van hacia adelante']),
 'hammer_curl': ('Hammer curl','Curl martillo',
   ['Palms facing each other','Squeeze at the top'],
   ['Palmas enfrentadas','Aprieta arriba'],
   ['Swinging','Rushing the descent'],
   ['Balancear','Bajar a las carreras']),
 'cable_curl': ('Cable curl','Curl en polea',
   ['Constant tension through the rep','Elbows still'],
   ['Tensión constante en toda la repetición','Codos quietos'],
   ['Leaning back','Half reps'],
   ['Inclinarte hacia atrás','Medias repeticiones']),
 'barbell_curl': ('Barbell curl','Curl con barra',
   ['Shoulder-width grip','Elbows stay by your sides'],
   ['Agarre al ancho de los hombros','Los codos se quedan a los costados'],
   ['Swinging the hips','Too heavy'],
   ['Balancear la cadera','Demasiado peso']),
 'triceps_pushdown': ('Triceps pushdown','Extensión de tríceps en polea',
   ['Elbows pinned, push down until straight','Control the way up'],
   ['Codos fijos, empuja hasta estirar','Controla la subida'],
   ['Elbows flaring','Leaning over the cable'],
   ['Codos abiertos','Inclinarte sobre la polea']),
 'overhead_triceps_extension': ('Overhead triceps extension','Extensión de tríceps sobre la cabeza',
   ['Elbows close to the head','Lower behind the head, extend fully'],
   ['Codos cerca de la cabeza','Baja detrás de la cabeza y extiende por completo'],
   ['Elbows drifting apart','Arching the back'],
   ['Codos que se separan','Arquear la espalda']),
 'bench_dip': ('Bench dip','Fondos en banco',
   ['Hands on the bench, feet forward','Lower until the elbows are at 90 degrees'],
   ['Manos en el banco, pies adelante','Baja hasta que los codos queden a 90 grados'],
   ['Going too deep','Shoulders rolling forward'],
   ['Bajar demasiado','Hombros que ruedan hacia adelante']),
 'skull_crusher': ('Skull crusher','Extensión de tríceps acostado',
   ['Lower toward the forehead','Elbows pointing at the ceiling'],
   ['Baja hacia la frente','Codos apuntando al techo'],
   ['Elbows flaring','Turning it into a press'],
   ['Codos abiertos','Convertirlo en un press']),
 'plank': ('Plank','Plancha',
   ['Straight line from head to heels','Squeeze the glutes and abs'],
   ['Línea recta de la cabeza a los talones','Aprieta glúteos y abdomen'],
   ['Hips sagging or too high','Holding your breath'],
   ['Cadera hundida o demasiado alta','Aguantar la respiración']),
 'side_plank': ('Side plank','Plancha lateral',
   ['Elbow under the shoulder','Hips stacked and lifted'],
   ['Codo debajo del hombro','Cadera alineada y levantada'],
   ['Hips dropping','Rolling forward'],
   ['Cadera que cae','Rodar hacia adelante']),
 'dead_bug': ('Dead bug','Bicho muerto',
   ['Lower back pressed into the floor','Extend the opposite arm and leg slowly'],
   ['Espalda baja pegada al piso','Extiende brazo y pierna opuestos despacio'],
   ['Back arching off the floor','Rushing'],
   ['Espalda que se arquea','Ir a las carreras']),
 'hanging_knee_raise': ('Hanging knee raise','Elevación de rodillas colgado',
   ['Knees to chest, then lower with control','Slight posterior tilt of the pelvis'],
   ['Rodillas al pecho y baja con control','Ligera retroversión de la pelvis'],
   ['Swinging','Using the hip flexors only'],
   ['Balancearte','Usar solo los flexores de cadera']),
 'cable_crunch': ('Cable crunch','Crunch en polea',
   ['Rope behind the head','Curl the ribs toward the hips'],
   ['Cuerda detrás de la cabeza','Enrolla las costillas hacia la cadera'],
   ['Pulling with the arms','Hinging at the hips'],
   ['Jalar con los brazos','Doblar la cadera']),
 'pallof_press': ('Pallof press','Press Pallof',
   ['Cable at chest height, side-on','Press out and hold, do not let it twist you'],
   ['Polea a la altura del pecho, de lado','Extiende y aguanta sin dejar que te gire'],
   ['Twisting toward the cable','Too much weight'],
   ['Girar hacia la polea','Demasiado peso']),
 'bicycle_crunch': ('Bicycle crunch','Crunch bicicleta',
   ['Elbow to opposite knee','Slow and controlled'],
   ['Codo a la rodilla opuesta','Lento y controlado'],
   ['Pulling on the neck','Going too fast'],
   ['Jalar del cuello','Ir demasiado rápido']),
 'burpee': ('Burpee','Burpee',
   ['Chest to the floor, then jump','Land softly'],
   ['Pecho al piso y luego salta','Aterriza suave'],
   ['Sagging through the push-up','Landing stiff-legged'],
   ['Hundirte en la flexión','Aterrizar con las piernas rígidas']),
 'jump_squat': ('Jump squat','Sentadilla con salto',
   ['Land soft, absorb into the next rep','Arms swing for height'],
   ['Aterriza suave y absorbe hacia la siguiente','Los brazos ayudan a ganar altura'],
   ['Landing with locked knees','Knees caving'],
   ['Aterrizar con las rodillas bloqueadas','Rodillas hacia adentro']),
 'mountain_climber': ('Mountain climber','Escalador',
   ['Hands under the shoulders','Drive the knees fast, hips low'],
   ['Manos bajo los hombros','Lleva las rodillas rápido, cadera baja'],
   ['Hips rising','Bouncing the shoulders'],
   ['Cadera que sube','Rebotar los hombros']),
 'jumping_jack': ('Jumping jack','Saltos de tijera',
   ['Light on the feet','Arms all the way overhead'],
   ['Ligero sobre los pies','Brazos hasta arriba'],
   ['Landing flat-footed','Half arm swing'],
   ['Aterrizar con todo el pie','Mover los brazos a medias']),
 'farmers_carry': ('Farmer\'s carry','Caminata del granjero',
   ['Stand tall, shoulders back','Walk with short, quick steps'],
   ['Erguido, hombros atrás','Camina con pasos cortos y rápidos'],
   ['Leaning to one side','Shrugging'],
   ['Inclinarte hacia un lado','Encoger los hombros']),
 'dumbbell_swing': ('Dumbbell swing','Swing con mancuerna',
   ['Hinge, then snap the hips forward','Arms are just a rope'],
   ['Bisagra y luego lanza la cadera hacia adelante','Los brazos son solo una cuerda'],
   ['Squatting instead of hinging','Lifting with the arms'],
   ['Hacer sentadilla en vez de bisagra','Levantar con los brazos']),
 'bike_intervals': ('Bike intervals','Intervalos en bicicleta',
   ['Hard effort, then easy spin','Keep the cadence up'],
   ['Esfuerzo fuerte y luego pedaleo suave','Mantén la cadencia alta'],
   ['Starting the hard bit too hard','Slumping over the bars'],
   ['Empezar el tramo fuerte demasiado fuerte','Encorvarte sobre el manubrio']),
 'rower_intervals': ('Rower intervals','Intervalos en remo',
   ['Legs, then back, then arms','Long, smooth strokes'],
   ['Piernas, luego espalda, luego brazos','Remadas largas y fluidas'],
   ['Pulling with the arms first','Rounding the back'],
   ['Jalar primero con los brazos','Redondear la espalda']),
}

muscles = {
 'en': {'quads':'Quads','hamstrings':'Hamstrings','glutes':'Glutes','calves':'Calves','chest':'Chest','back':'Back','shoulders':'Shoulders','biceps':'Biceps','triceps':'Triceps','abs':'Abs'},
 'es': {'quads':'Cuádriceps','hamstrings':'Isquiotibiales','glutes':'Glúteos','calves':'Pantorrillas','chest':'Pecho','back':'Espalda','shoulders':'Hombros','biceps':'Bíceps','triceps':'Tríceps','abs':'Abdomen'},
}
implements = {
 'en': {'barbell':'Barbell','dumbbell':'Dumbbells','machine':'Machine','cable':'Cable','bodyweight':'Bodyweight'},
 'es': {'barbell':'Barra','dumbbell':'Mancuernas','machine':'Máquina','cable':'Polea','bodyweight':'Peso corporal'},
}
categories = {
 'en': {'compound':'Compound','accessory':'Accessory','isolation':'Isolation','core':'Core','conditioning':'Conditioning'},
 'es': {'compound':'Compuesto','accessory':'Accesorio','isolation':'Aislamiento','core':'Core','conditioning':'Acondicionamiento'},
}

for i, locale in enumerate(['en','es']):
    path = pathlib.Path(f'messages/{locale}.json')
    data = json.loads(path.read_text())
    ex = {}
    for eid, v in X.items():
        name = v[0] if locale=='en' else v[1]
        cues = v[2] if locale=='en' else v[3]
        mistakes = v[4] if locale=='en' else v[5]
        ex[eid] = {'name': name, 'cue1': cues[0], 'cue2': cues[1], 'mistake1': mistakes[0], 'mistake2': mistakes[1]}
    data['exercises'] = ex
    data['muscles'] = muscles[locale]
    data['implements'] = implements[locale]
    data['categories'] = categories[locale]
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
print('exercises written:', len(X))
