"""Generates src/types/database.ts from the live schema in Postgres, in the
shape supabase-js expects. Used because `supabase gen types` needs Docker.
Run: python3 scripts/gen-db-types.py (DATABASE_URL or local defaults)."""
import os, subprocess, json

url = os.environ.get('DATABASE_URL', 'postgresql://postgres@127.0.0.1:5432/plates')

def q(sql):
    out = subprocess.run(['psql', url, '-tAc', sql], capture_output=True, text=True, check=True).stdout
    return [line.split('|') for line in out.strip().splitlines() if line]

TS = {
 'uuid':'string','text':'string','character':'string','character varying':'string',
 'integer':'number','numeric':'number','bigint':'number','double precision':'number','real':'number',
 'boolean':'boolean','date':'string','timestamp with time zone':'string','timestamp without time zone':'string',
 'jsonb':'Json','json':'Json',
}

tables = [r[0] for r in q("select table_name from information_schema.tables where table_schema='public' and table_type='BASE TABLE' order by table_name")]

def cols(table):
    rows = q(f"""select column_name, data_type, is_nullable, column_default is not null
                 from information_schema.columns where table_schema='public' and table_name='{table}' order by ordinal_position""")
    return [(c, TS.get(t, 'unknown'), n == 'YES', d == 't') for c, t, n, d in rows]

out = []
out.append("// Generated by scripts/gen-db-types.py from the Postgres schema. Do not edit by hand.")
out.append("export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]\n")
out.append("export type Database = {\n  public: {\n    Tables: {")
for t in tables:
    cs = cols(t)
    out.append(f"      {t}: {{")
    out.append("        Row: {")
    for c, ty, nullable, _ in cs:
        out.append(f"          {c}: {ty}{' | null' if nullable else ''}")
    out.append("        }")
    out.append("        Insert: {")
    for c, ty, nullable, has_default in cs:
        opt = '?' if nullable or has_default else ''
        out.append(f"          {c}{opt}: {ty}{' | null' if nullable else ''}")
    out.append("        }")
    out.append("        Update: {")
    for c, ty, nullable, _ in cs:
        out.append(f"          {c}?: {ty}{' | null' if nullable else ''}")
    out.append("        }")
    out.append("        Relationships: []")
    out.append("      }")
out.append("    }")
out.append("    Views: Record<string, never>")
out.append("""    Functions: {
      group_weekly_summary: {
        Args: { p_group_id: string }
        Returns: { member_id: string; display_name: string; sessions_done_this_week: number; streak_days: number }[]
      }
      join_group_with_code: { Args: { p_code: string }; Returns: string }
      create_group: { Args: { p_name: string }; Returns: string }
      export_my_data: { Args: Record<string, never>; Returns: Json }
      delete_my_account: { Args: Record<string, never>; Returns: undefined }
      training_streak: { Args: { p_user_id: string }; Returns: number }
      is_group_member: { Args: { p_group_id: string; p_user_id: string }; Returns: boolean }
      is_group_owner: { Args: { p_group_id: string; p_user_id: string }; Returns: boolean }
    }
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}

type PublicSchema = Database['public']
export type Tables<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Row']
export type TablesInsert<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof PublicSchema['Tables']> = PublicSchema['Tables'][T]['Update']""")
open('src/types/database.ts', 'w').write('\n'.join(out) + '\n')
print('tables:', len(tables), tables)
